services:
  - type: web
    name: scatch
    env: node
    buildCommand: npm install
    startCommand: npx nodemon
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://pratyushbhargava6:az3CycSvzhmLyYfB@cluster0.wcg4j.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: PORT
        value: 10000